### ISSUE TITLE
*event_account_update in ActionPlan 

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#1059]
Hello Dan,
Following our meeting, opening an issue for *event_account_update in ActionPlan.
To be able to process BalanceUpdate events even when no accounting happens.
Thanks for assistance,
Michael

**Comment by danbogos** [comment]
hi @muxalko 

The action is named "*publish_account" and it should publish both account as well as each individual balances to ThresholdS(conns defined in RALs for now since there should be no separation between RALs and scheduler). 
Did not get a chance to test it, so I would appreciate any feedback on it.

Thanks,
DanB
