### ISSUE TITLE
ApierV2.SetAccount don't add balances and triggers

### ISSUE THREAD

**Issue by YohaiAllouche** [cgrates/cgrates#1082]
I try to set account via ApierV2.SetAccount , the account is created but with no balances and no triggers.

Actions.csv
#ActionsId[0],Action[1],ExtraParameters[2],Filter[3],BalanceId[4],BalanceType[5],Directions[6],Categories[7],DestinationIds[8],RatingSubject[9],SharedGroup[10],ExpiryTime[11],TimingIds[12],Units[13],BalanceWeight[14],BalanceBlocker[15],BalanceDisabled[16],Weight[17]
TOPUP_60_IL,*topup_reset,,,PKG60MINS,*voice,*out,voice,*any,,,+30d,,60m,10,false,false,10
TOPUP_60_IL,*topup_reset,,,PKG60SMS,*sms,*out,sms,*any,,,+30d,,60,10,false,false,10

ActionPlans.csv
PACKAGE_IL,TOPUP_60_IL,*asap,10
PACKAGE_IL,LOG_WARNING,*asap,10

ngrep:

#######
T 2018/05/13 16:32:41.274145 192.168.XXX,YYY:36026 -> 192.168.XXX.ZZZ:2012 [AP]
{"params": [{"ActionPlanID": ["PACKAGE_IL"], "ReloadScheduler": true, "Account": "972557XXXX", "AllowNegative": false, "Disabled": false, "ActionTriggerOverwrite": true, "ActionPlansOverwrite": true, "tenant": "num2.il", "ActionTriggerID": ["STANDARD_TRIGGERS"]}], "id": 1, "method": "ApierV2.SetAccount"}
##
T 2018/05/13 16:32:41.277597 192.168.XXX.ZZZ:2012 -> 192.168.XXX,YYY:36026 [AP]
{"id":1,"result":"OK","error":null}

When using ApierV1.SetAccount it is working fine.

Regards,
Yohai

**Comment by TeoV** [comment]
Hi YohaiAllouche,
Your API call has wrong parameters (for example "tenant" is with grand "T" = > "Tenant":"num2.il" ,
"ActionPlanID" and "ActionTriggerID" have  "s" at final )  . 
A recommendation is to use cgr-console(it's like linux console but just for CGRateS), otherwise, you can checks parameters and API at :  
https://godoc.org/github.com/cgrates/cgrates/apier

In your case these two links. 
https://godoc.org/github.com/cgrates/cgrates/apier/v2#ApierV2.SetAccount 
https://godoc.org/github.com/cgrates/cgrates/apier/v2#AttrSetAccount

{
	"params": [{
		"ActionPlanID**s**": ["PACKAGE_IL"],
		"ReloadScheduler": true,
		"Account": "972557XXXX",
		"AllowNegative": false,
		"Disabled": false,
		"ActionTriggerOverwrite": true,
		"ActionPlansOverwrite": true,
		"**T**enant": "num2.il",
		"ActionTriggerID**s**": ["STANDARD_TRIGGERS"]
	}],
	"id": 1,
	"method": "ApierV2.SetAccount"
}

Thanks,
TeoV
