### ISSUE TITLE
Feature request: default  balance prefix setting \ API parameter

### ISSUE THREAD

**Issue by Gooodzi** [cgrates/cgrates#1187]
Hello Dear CGRates Team!

It would be great to have the possibility to set up default balance prefix for a system (for example as an option in cgrates.json config file). As far as I know - currently system uses "ns" as default one for values without prefix, this makes it pretty difficult to migrate from older versions where "s" was the default prefix, and it becomes harder to check\track all the changes necessary to be made, it concerns rates, charges and user balances - and currently the only way is to change\recreate those values manually.

This also relates to API for charges/balance operations - it would have higher usability if we can declare additional parameter for API queries to define in which scope the values transferred should be processed. This may help to adapt systems operating with CGRates via API after migration to newer CGRates versions with minimal efforts\changes.

Please share your opinion on this idea and possibility of its implementation.

Thank you in advance,
Best regard

**Comment by danbogos** [comment]
hey @Gooodzi 

Thank you for your input.
Unfortunately the headache of maintaining such setting in the code is higher than the advantage. We use specific functions to parse defaults and then we should also start looking into all APIs to add this functionality. I don't think there will be any other change between ns->s since we use Go defaults now (ns) hence the maintenance for the future should be consistent. Sorry for the inconvenience of the upgrade however the downside of not doing it was more negative unfortunately :(.
All the best,
DanB
