### ISSUE TITLE
Feature Request: 3GPP Sy Interface support

### ISSUE THREAD

**Issue by chrisgis333** [cgrates/cgrates#1200]
It would be great to see Sy Interface support in CGRateS.
Other commercially available OCS's has it.
Is it possible to add Sy Interface based on http://www.3gpp.org/ftp//Specs/archive/29_series/29.219/29219-f10.zip?

I am working on this feature on side. I can contribute in adding this feature.

**Comment by danbogos** [comment]
hey @chrisgis333 

Thanks for this.

Yes, we consider adding it. Right now we are in the process of redesigning our Diameter implementation so I think it will be good to catch up on this issue again once that is finished. We plan Diameter to be more generic (supporting more commands), so there are chances you will be able to have Sy directly out of processor templates.

DanB

**Comment by chrisgis333** [comment]
hej @danbogos 
Any idea how long it might take?
closer to month or a year

**Comment by chrisgis333** [comment]
@danbogos 
Hej,
I'm little confused why You closed this issue.
New version of diameter is merged but I can't find the way to configure Sy interface flow.

I can of course configure diameter Spending-Limit messages but don't know how force CGRateS to generate mandatory reply fields.
Basic scenario;
Spending-Limit-Request (Account) ->
<- Spending-Limit-Answer (Policy-Counter-Status-Report)
where Policy-Counter-Status-Report looks:
Policy-Counter-Identifier: DATA
Policy-Counter-Status: FULL
if DATA balance is not empty on account
or 
Policy-Counter-Identifier: DATA
Policy-Counter-Status: LIMITED
if there is no resources for data transmision.

Can You help me configure this scenario or guide me how to change CGRateS for this scenario to work?

Krzysiek

**Comment by chrisgis333** [comment]
More complicated scenario is even worse:
Spending-Limit-Request (Account) ->
<- Spending-Limit-Answer (Policy-Counter-Status-Report)
<-Spending-Status-Notification-Request(Policy-Counter-Status-Report)
Spending-Status-Notification-Answer -> (Result-Code)

How to initiate Message from CGRateS?

**Comment by danbogos** [comment]
hey @chrisgis333 

Closed all the diameter issues at once since we don't longer know which ones apply to the new implementation (from our POV the new implementation should be generic enough, at least for answers CGRateS needs to send).
Regarding replies, please check the sample files we have posted for diameter agent here:
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/diamagent/data.json

It is important to understand that part before deciding if Sy needs further development.

Regarding initiating message from CGRateS, need to understand what should trigger it. We have thought about adding some but for the moment only STR makes sense from the point of view of CGRateS functionality. Please let me know about further ones which you need to apply.

Thanks,
DanB

PS: I think it will be more beneficially for the community if we continue with questions on the google group so people can also learn from the answers, so if OK with you, please open a new thread there and as soon as we decide it is needed to develop a new feature, will post it here.
