### ISSUE TITLE
 Multi-file JSON for http_agent 

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1311]
Hi,

Attached is loading correctly, but it's not seeing all the request processors.

The only example I've seen is at https://github.com/cgrates/cgrates/tree/master/data/conf/samples/multifiles

I guessed it would concat all files before loading it as JSON (not read source code yet), which didn't work (EOF parsing errors as no files were valid JSON). So I've now done it with matching ID's across files thinking that would merge the JSON once parsed.

[multi-json.zip](https://github.com/cgrates/cgrates/files/2596793/multi-json.zip)

Thanks,
Gavin.

**Comment by TeoV** [comment]
Hi Gavin,
We have analyzed your config and it's declared wrong.
You need to maintain the nesting level in all .json files. (all files should contain "http_agent":{...}) 

Thanks,
TeoV

P.S.
You can guide yourself after the sample from multifiles.

**Comment by ghenry** [comment]
Hi TeoV,

So looking at https://github.com/cgrates/cgrates/commit/0d2fef4d085524683bdf54263b89326e739c4a95 I have to have lots of duplicated config statements (session_conn etc)?

Thanks.

**Comment by ghenry** [comment]
Or one in the first file and the rest are OK?

**Comment by TeoV** [comment]
Hi Gavin,
You can choose to not put them if they are the same as in the first file. I put them to reflect that in other files we change some of them and the rest remain the same.
As you can see : 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/multifiles/a.json#L29 here we have a temple (id=conecto1 with 2 request processor) 
In the second file : 
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/multifiles/b/b.json we change some fields for conecto1 ( url became /newConecto and address for session_conn 120.0.0.2 and the rest remain the same) 
In the third file we add a new temple (conecto_xml)
https://github.com/cgrates/cgrates/blob/master/data/conf/samples/multifiles/c.json#L23 

Good luck and if you have other questions please post on google groups because this is closed and if someone have the same problem could easy check there instead here. 
Thanks,
TeoV
