### ISSUE TITLE
Filters/Thresholds for multiple balances

### ISSUE THREAD

**Issue by pustovoytenko** [cgrates/cgrates#1420]
Hi,

For example, you have accounts with *monetary and *sms balances and accounts have external sms services that charged as external CDRs. In order to have possibility to block external services,
it necessary to generate an action when both balances = 0 in the same time.
It would be nice to have possibility to add Filters/Thresholds for multiple balances.

Thanks

**Comment by Trial97** [comment]
Hi @pustovoytenko,

This should be fixed in the latest master as now we send the account summary on balance update.
You can filter the thresholds like this: https://github.com/cgrates/cgrates/blob/master/apier/v1/thresholds_it_test.go#L879-L880
Also, you can filter over the information from the account in any filter using the `~*account`: https://github.com/cgrates/cgrates/blob/master/general_tests/filters_it_test.go#L569-L581

Thanks,
Trial97
