### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by ghenry** [cgrates/cgrates#1448]
Hi all,

Was having a play in master as I wanted to reach for some low hanging fruit to write a test for. I used this https://blog.golang.org/cover for guidance. 

Attached is the report. Is there any thing I could look at that won't distract you guys? Are these types of metrics of use as I know you operate TDD anyway, so all the important things are covered.

Thanks,
Gavin.
[cover.zip](https://github.com/cgrates/cgrates/files/2933372/cover.zip)

**Comment by danbogos** [comment]
hey Gavin,

We are aware about not having coverage in unit tests for all the possible cases, however I think the integration tests are doing good a job covering the overall e2e. For the moment we have parked this on our side as nice-to-have. Will most probably come back into improving the test coverage after we finish with the high priority tasks we got for getting a release out.
As a side note, we also plan getting one more developer on board so that would be a good way for him to start.

Cheers,
DanB

**Comment by ghenry** [comment]
Hi Dan,

Cool, no problem. You guys know what you are going anyway, just
thought I'd have a play. I love testing so was just keen to help some
how.

Thanks.

**Comment by danbogos** [comment]
Gavin,

Appreciated :). You already did enough by providing us with the right info ;).

Thanks,
DanB

**Comment by ghenry** [comment]
Good. That's something!
