### ISSUE TITLE
CGrateS Service not getting up

### ISSUE THREAD

**Issue by rccess** [cgrates/cgrates#1633]
Hello All , 

There is one bug found in 2.11 , Cgrates are not getting up 

Already tried to restart redis server and followed by logs but no clue

![image](https://user-images.githubusercontent.com/32220165/61386586-2b9fc400-a8d2-11e9-8fab-cfb7f7f1b54b.png)

please advice

thanks

**Comment by TeoV** [comment]
Hi @rccess,

This is not a CGRateS problem, it's a Redis problem and the log said clearly what's the problem is: " Redis is running in protected mode because protected mode is enabled... In this mode  connections are accepted only from loopback interface...etc..."

Thanks,
TeoV

P.S.: In case you have questions next time please post them on google groups ( https://groups.google.com/forum/#!forum/cgrates )
