### ISSUE TITLE
Documention problem

### ISSUE THREAD

**Issue by annabelle1984** [cgrates/cgrates#1650]
I am new to cgrates and I think the read the doc documentation is for very old version as for example in destinations table there are more fields than just id and prefix and I have no idea what are them.
is there newer version of documentation out there?

**Comment by TeoV** [comment]
Hi @annabelle1984,

Please send the link where the problem is and we will try to fix it.
Also if you are new we recommend starting from the tutorial ( https://github.com/cgrates/cgrates/tree/master/data/tariffplans/tutorial ) 
Regarding documentation, if you check the code you will see that we have more than 5000 tests ( if you look at them they can be very good documentation for this software).

Thanks,
TeoV

**Comment by annabelle1984** [comment]
documentation is not clear and it takes me lots of time to figure out what should I do, its near one week and I even couldnt config this thing that seems so easy
for example here for setting version https://cgrates.readthedocs.io/en/latest/tut_cgrates_installs.html
we have this command https://cgrates.readthedocs.io/en/latest/tut_cgrates_installs.html this cgr-migrator -stordb_passwd="CGRateS.org" -migrate="*set_versions" this command does not work at all and show me just help section and when you look at help you will find out that there is no such command for migrate
second: here https://cgrates.readthedocs.io/en/latest/tut_jitsi_installs.html you have this : 1001/CGRateS.org for user/pass but in config file in tutorial folder pass is sth else
third, here https://cgrates.readthedocs.io/en/latest/tut_cgrates_usage.html there is this command cgr-loader -verbose -path=/usr/share/cgrates/tariffplans/tutorial i assume by running this it will fill my mysql database but there is no error and nothing happens.
Every thing in documentation is messed up nothing is clear, there is no path to describe clearly for a simple call do this steps this will happens and here is your result 
input and out put of system is not clear at all, just layered folders with no clear documentation of usage

**Comment by TeoV** [comment]
Hi @annabelle1984,

The documentation is for rc7 which is released and parts of rc8. The master is permanently evolved and we haven't a released for it, that's one of the main reason that the documentation remains outdated.
Regarding the first problem we changed the flag from -migrate to -exec ( if you typed cgr-migrator -help you should see all available flags ) 
Regarding the second "thing" this isn't a problem. We have two types of database ( DataDB which can be Redis Mongo or InternalDatabase a.k.a caching and StorDb which can be MySQL Mongo Postgres or InternalDatabase ). This part is explained here ( https://cgrates.readthedocs.io/en/latest/architecture.html ) 
A large part of the documentation was built by community members like you.
Our primary focus is the development of the software and we were hoping that community members like you will help us with building the docs
Since you have found the problemes we would be happy if you could let others benefits of the answers we provided to you and correct the documentation in the way you think it would be more obvious.
We are also happy to answer to any king of questions in order so you can improve the documentation.

Thanks,
TeoV
