### ISSUE TITLE
Feature Request: Return correct HTTP status codes in API responses

### ISSUE THREAD

**Issue by mehrdadep** [cgrates/cgrates#1823]
Return correct `HTTP` responses for errors in all `API` responses. for example this `API` call should return 404 instead of 200 when `Test` does not exists:

```
{
	"id":"54874585755421",
	"jsonrpc":"2.0",
	"method":"ApierV1.GetTPTiming",
	"params":[
			{
					"TPid": "TRP_DEFAULT",
					"ID": "Test"
			}
	]
}
```
Right now, this is the response with status code 200:
```
{
  "id": "1231231",
  "result": null,
  "error": "NOT_FOUND"
}
```

**Comment by danbogos** [comment]
hi @mehrdadep 

since JSON over HTTP is an application over HTTP the logic is a bit different than you expect it. When you call the URL, the feedback in the HTTP response codes is regarding that URL and not regarding the application content. Imagine calling /jsonrpc with  "ApierV1.GetTPTiming". If we return 404 as HTTP reply code, it will mean that the url "/jsonrpc" does not exist on the server, not that the ID "Test" does not exist in the JSON-RPC application at "ApierV1.GetTPTiming". What you are trying to achieve is HTTP REST but here we are talking about different RPC protocol all together.

Will close the issue since it cannot happen.

Thanks,
DanB

**Comment by mehrdadep** [comment]
hi @danbogos 

since JSON-RPC 2.0 [Specification](https://www.jsonrpc.org/specification)  has a standard for returning errors, is it possible to consider this specification in responses?

> When a rpc call encounters an error, the Response Object MUST contain the error member with a value that is a Object with the following members:
> 
> code
> A Number that indicates the error type that occurred.
> This MUST be an integer.
> message
> A String providing a short description of the error.
> The message SHOULD be limited to a concise single sentence.
> data
> A Primitive or Structured value that contains additional information about the error.
> This may be omitted.
> The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).

```
--> {"jsonrpc": "2.0", "method": 1, "params": "bar"}
<-- {"jsonrpc": "2.0", "error": {"code": -32600, "message": "Invalid Request"}, "id": null} 
```

**Comment by danbogos** [comment]
hi @mehrdadep 

Unfortunately Go will only support JSON-RPC 1.0 (https://golang.org/pkg/net/rpc/jsonrpc/). You can add an issue for the future but cannot tell for sure when this will happen.

DanB
