### ISSUE TITLE
Basic Installation -  Active: failed (Result: resources)

### ISSUE THREAD

**Issue by dv8inpp** [cgrates/cgrates#1894]
I am using a Debian 9 VM under Windows 10 Hyper V. I have followed the instructions on https://cgrates.readthedocs.io/en/latest/installation.html#id2 and watched the you tube video FreeSwitch-CGRatES Integration Tutorial 7/17/19. 

In the video tutorial Dan shows the service is running straight after installing the deb package (22:50). After following the written installation guide I get the following error when trying to start the service.

Active: failed (Result: resources)

How can I resolve this? I checked the Google groups but wasn't able to find any answers.

If I run cgr-engine -logger=*stdout I get:
2020/01/23 22:28:33 CGRateS <1510170> [INFO] <CoreS> starting version <CGRateS@v0.9.1~rc8-20200123160607-fddea1839170><go1.13>
2020/01/23 22:28:33 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2020/01/23 22:28:33 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2020/01/23 22:28:33 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2020/01/23 22:28:33 rpc.Register: method "Call" has 4 input parameters; needs exactly three
2020/01/23 22:28:33 rpc.Register: method "Call" has 4 input parameters; needs exactly three

I am trying to use mongo as I have had one succesful intallation out of 10 attempts and it worked with that, the only issue I had was with the cgr-migrator line that reads
cgr-migrator -stordb_passwd="CGRateS.org" -datadb_type="mongo" -datadb_port=27017 -stordb_type="mongo" -stordb_port=27017 -migrate="*set_versions" and I needed to change -migrate to -exec

**Comment by danbogos** [comment]
hi  @dv8inpp 

When you install the CGRateS first time, it has no services running. As an optimization, if there are no services requesting it, we don't open any RPC ports out. 
Once you have CGRateS installed, I suggest starting with the FreeSWITCH tutorial configs, as explained [here](https://cgrates.readthedocs.io/en/latest/tut_freeswitch_json.html)
If you want to skip the automatic process, you can start CGRateS manually with the command:
`cgr-engine -config_path=data/tutorials/fs_evsock/cgrates/etc/cgrates/cgrates.json -logger=*stdout
`
This will start the necessary services, connect to your FreeSWITCH instance and redirect the logging to your stdout so you can see things faster.

Regarding your migrator, once you have your cgrates config properly set in the .json folder, I suggest the following command:
`cgr-migrator -exec=*set_versions -config_path=/path/to/your/config`.
This takes care about all the db settings you need to do.

I hope this helps.

DanB

PS: Please use our google group for getting help in the future since we keep the github for archiving issues and feature requests.
