### ISSUE TITLE
CGRateS random crashes

### ISSUE THREAD

**Issue by kristina258** [cgrates/cgrates#2569]
Hello,

our system runs on Debian 10. We use CGRateS with Kamailio Agent.
Kamailio is running the newest version 5.4.2 and CGRateS version is v0.10.2~dev-20200929133638-231adb128486.

We experience random CGRateS crashes when the system is under load. 

We tried to upgrade  CGRateS  to newer verion v0.10.3~dev-20201207134928-19f30a418dcb but the behavior was still the same. CGRateS always crashed after some time.

cgrates.strace attached
[cgrates.strace.log](https://github.com/cgrates/cgrates/files/5735538/cgrates.strace.log)

I noticed right now, that the first line in strace.log shows that we are starting version: **CGRateS@v0.11.0~dev-20201210091009-7e566ead49b6**
Anyway, when I run cgr-engine --version it shows **CGRateS@v0.10.2~dev-20200929133638-231adb128486**.

Thank you!

**Comment by danbogos** [comment]
hi @kristina258 

It appears there is something wrong with your session refunds. In order to understand the reason for it, please capture the traffic between sessions and rals (rals_conns needs to be on 2012, transport *json) and send it over to me (either here or directly if you worry about sensitive information). It is important to have the information by the time of the crash inside (timestamp of the syslog needs to match the one in ngrep).

Thanks,
DanB

**Comment by Trial97** [comment]
Hi @kristina258,

We pushed a possible fix in the v0.10 branch.
Please update and retest.

Thanks,
Trial97

**Comment by kristina258** [comment]
Hi,

we tested and the issue seems to be fixed.

Thank you so much!

Kristina

**Comment by Trial97** [comment]
Hi @kristina258,

We will consider this issue resolved and close this issue.
Feel free to reopen this issue if needed.

Thanks,
Trial97
