### ISSUE TITLE
evapi_async_relay throws w_evapi_async_relay(): failed to suspend request processing

### ISSUE THREAD

**Issue by andrewvmail** [cgrates/cgrates#307]
Right after CGR_CALL_START function inside the sample kamailio-cgrates.cfg it looks like there is a problem with the evapi_async_relay function. 

When changed to evapi_relay as per Dan instructions on Google Groups everything seem to be working again. Submitting an issue for this.

Thank you
A

**Comment by voxbit1** [comment]
I reported the issue and the workaround on the forum.  https://groups.google.com/forum/#!topic/cgrates/LokoX6ydMGo

I believe the issue is that evapi_async_relay() attempts to suspend the dialog.  Whereas evapi_relay() simply sends the message to CGRates and carry on.  ref: http://kamailio.org/docs/modules/4.3.x/modules/evapi.html#evapi.f.evapi_async_relay

It seems to me that the dialog cannot be suspended at that time as the call has just been answered.

**Comment by danbogos** [comment]
Hey Guys,

Sorry for taking me so long but I have finally analyzed the issue and you were both right. It appears that using evapi_async_relay was not used properly in CALL_START and CALL_END (although it worked with older versions of Kamailio since we have tests for it). Anyway, since these routes are themselves called asynchronously I think that was the reason Kamailio could not suspend the transaction.

Let me know if any issues.

DanB
