### ISSUE TITLE
[BUG] AttributeProfile - invalid length of bytes for decoding time

### ISSUE THREAD

**Issue by vtzan** [cgrates/cgrates#3401]
Dear Team,

I am using latest v0.10 and somehow I have managed to create an attribute profile which returns this result when trying APIerSv1.GetAttributeProfile:

```
{
    "id": "0",
    "result": null,
    "error": "SERVER_ERROR: msgpack decode error [pos 37]: invalid length of bytes for decoding time - expecting 4 or 8 or 12, got 15"
}
```

and APIerSv1.RemoveAttributeProfile says not found 

```
 {
    "id": "0",
    "result": null,
    "error": "NOT_FOUND"
}

```

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by porosnicuadrian** [comment]
Hello @vtzan,

Sorry for the delay, we found out that due to upgrading the ugoriji package(msgpqck decoding package) to latest version, the decoding of data which contains time values that were imported before upgrading is not in sync with the new one. We suggest you to just import the data again into the database with the same values in order to work properly.
Let me know if that works.

Thanks,
@porosnicuadrian

**Comment by vtzan** [comment]
Dear @porosnicuadrian,

This was exactly what I did and worked.
So case closed. Thank you for your help.

Best regards 

Vasilios Tzanoudakis
