### ISSUE TITLE
ApierV1.LoadDestination performance issue

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#35]
We have trying to move the Destinations from the StorDB over to the DataDB using the ApierV1.LoadDestination but the performance is painfully slow.  

It takes well over 20 mins to Load the Destinations of about 57095 rows into the DataDB.  The webserver actually times out after 10 mins.
SetTPDestinations completes in about  288 second(s). 

CGRates version: cgrates_0.9.1-rc6_amd64.deb (3rd Jan 2015) Also tested on earlier versions.
Postgres version 9.3 and 9.4

Any ideas?

Errol

**Comment by danbogos** [comment]
Hi Errol,

As discussed over IRC the reason you get performance issues is because of repeatedly calling SetDestination in short interval (50k+ times). Each call will cause a cache reload which takes about 2 seconds.
I have just modified the API not to reload all keys which hopefully will improve the 2 seconds in between, however the right way to do it in your case is via SetRatingPlan API (again as discussed over IRC).

The SetDestination has now also a PreventCacheReload parameter which you can call to cancel automatic reloads and only call CacheReload when you are done with loading destinations (this will again greatly improve performance).

Please upgrade and let me know how it works.

DanB

**Comment by ewsamuels** [comment]
Hi DanB,

Yes the error is there in the original post, here it is again: {"id":0,"result":null,"error":"not found"}
regards,
Errol

**Comment by danbogos** [comment]
Can u maybe capture/reproduce the postgres query? This should point you out if the data is found or not.

DanB

**Comment by ewsamuels** [comment]
Hi Dan,

I am not sure why you are not seeing my info but I also reproduced the postgres query to show that the info is in fact in the table.  I even took a screenshot and attached it.
![screen shot 2015-01-07 at 14 50 34](https://cloud.githubusercontent.com/assets/5496519/5647295/91db922a-967c-11e4-8ffd-cfbcba39f777.png)

**Comment by ewsamuels** [comment]
Hi DanB,
This is all I see in the log:

2015-01-07 15:26:22 UTC LOG:  execute 3: SELECT  * FROM "tp_destinations"  WHERE tpid = $1 AND tag = $2
2015-01-07 15:26:22 UTC DETAIL:  parameters: $1 = 'VOXPREM', $2 = 'Abkhazia_Fixed'
2015-01-07 15:26:22 UTC LOG:  execute 4: SELECT  * FROM "tp_destinations"  WHERE tpid = $1 AND tag = $2
2015-01-07 15:26:22 UTC DETAIL:  parameters: $1 = 'VOXPREM', $2 = 'Abkhazia_Fixed'
2015-01-07 15:26:22 UTC LOG:  statement: SET TIME ZONE 'UTC'

**Comment by ewsamuels** [comment]
Hi DanB,
As per your suggestion on IRC, I have called ApierV1.LoadDestination with the extra parameter param['PreventCacheReload'] = True and that did the trick.  All 57K destinations were loaded in 30 secs.

As you also mentioned I will do a ReloadCache after calling the API.

````
########
T 2015/01/07 15:58:20.047694 127.0.0.1:34889 -> 127.0.0.1:2012 [AP]
{"params": [{"DestinationId": "Zimbabwe_Premium", "PreventCacheReload": true, "TPid": "VOXPREM"}], "method": "ApierV1.LoadDestination", "id": 0}
##
T 2015/01/07 15:58:20.050155 127.0.0.1:2012 -> 127.0.0.1:34889 [AP]
{"id":0,"result":"OK","error":null}
````
Thanks

Errol
