### ISSUE TITLE
Rounding up 2 decimal places issue

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#357]
Hi DanB,
There seems to be an issue when Rounding *up to two decimal places calls seem to get rated at 1 cent per sec rather than the per minute rate / 60.

When we change to do a Round *middle with 5 decimal places the issue is not there.

This was found in the 15th Dec package.

Regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

As stated in another issue which you have opened, you will need to upgrade
to today's master since the package you are using (also out of dev sources)
is more than 1 month old and it is impossible for us to support all the
commits ever since.

Thanks for understanding
DanB
Am 21.01.2016 21:48 schrieb "Errol Samuels" <notifications@github.com>:

**Comment by danbogos** [comment]
Closing the issue since there was no feedback from @ewsamuels.

DanB
