### ISSUE TITLE
Suggestion for Rounding

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#361]
Hi Guys,
Sometime in December you changed the logic of the way the Rounding is applied to during the call rather than at the end of the call.

As per my discussion with rif I see that there is a perfectly valid reason for the change of logic.

The CGRates documentation states that
> When the session manager receives a call start event it will first check if the call is prepaid or postpaid. If the call is postpaid than the cost will be determined only once at the end of the call but if the call is prepaid there will be a debit operation every X seconds (X is configurable)

However, at the moment it seems the same method of rounding and debiting Prepaid is being applied to Postpaid accounts.  It might well be a configuration issue but I am not certain.

Any ideas?

Regards,

Errol

**Comment by danbogos** [comment]
Hey @ewsamuels 

The rounding is applied per each increment. The reason we have changed the logic in December was because we have noticed a bug: cost command was returning the price calculated as a whole and was different than the price deducted for prepaid calls.
The postpaid now works exactly the same as prepaid, we still calculate (and round) increments which you configure so no reason to consider them separately anymore.

The issue you are facing is of some other manner. You offer to your customers price per minute but you charge them per second (hence the rounding per second).

One fix would be to put in the system (and publish) the prices per second, which is not that manageable but correct way.

Since we have already noticed in the past this issue, we will be working on a method to correct rounding at the end of the call (since in prepaid we debit with the increments rounded - no other way than this due to real-time debits).

DanB

**Comment by ewsamuels** [comment]
Hi DanB,

Thanks for your reply.

As a work around I had suggested to the customer to use 30 / 1 billing with 5 decimals since the reason for Rounding Up in the first place was due to their Provider enforcing a 1 cent minimum call charge on short duration calls so by billing in 30 / 1 increments it protects them that minimum call charge.

Regards,

Errol
