### ISSUE TITLE
ApierV1.GetDestination Gives Unmarshaling Error

### ISSUE THREAD

**Issue by ruhnet** [cgrates/cgrates#3738]
I'm running version CGRateS@v0.11.0~dev-20220810121914-ac483dd76031

When I query ApierV1.GetDestination for a valid destination, (whether created directly or loaded via tariff plan), this error is returned:
`json: cannot unmarshal object into Go value of type string`
I tried calling the API via curl on 2080 and also with telnet on 2012, with identical results (which is to be expected).

Example of steps to reproduce:
1. Create a destination for example with ID of `DEST_UK`
2. Query API to retrieve the destination:
```
curl http://localhost:2080/jsonrpc -d '{ "method": "ApierV1.GetDestination", "id": 1, "params": [{ "ID":"DEST_UK" }] }' 
```
3. Result:
```
{
  "id": 1,
  "result": null,
  "error": "json: cannot unmarshal object into Go value of type string"
}
```

**Comment by ruhnet** [comment]
Same error applies to `ApierV1.GetRatingPlan`

**Comment by ionutboangiu** [comment]
Hi Ruel,

There are a couple things that are wrong with your API request. The name of the method has a missing letter ("ApierV1" should be "APIerSv1") and "params" should be a plain string rather than a json object. In the end the request you are looking for is the following: {"method":"APIerSv1.GetDestination","params":["DEST_UK"],"id":1}. The same thing applies to GetRatingPlan. Hope this was useful.

Thanks,
Ionuț

**Comment by ruhnet** [comment]
Got it. Thank you---I see I must have read the docs wrong, as they of course match what you just told me (sorry about that). I am in the process of implementing a subset of the CGRateS APIs into an Elixir module so have been going through quite a few of the methods available and wrapping them. I've been using the "ApierV1.methodname" format on all of them, which I need to correct. Thanks again.
