### ISSUE TITLE
CGRates failing when testing with SIPP

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#377]
I have just been testing the latest package and found cgrates crashing.

At first I thought it was when it was under load but further testing showed it to be when suddenly shutting down many calls, ie a ctrl-c from sipp with 750+ concurrent calls on.

Attached is the strace
[strace.txt](https://github.com/cgrates/cgrates/files/142961/strace.txt)

**Comment by danbogos** [comment]
Hi @DigiDaz 

It appears that the reason of the crash is the database connection. CGRateS is trying to revert a transaction but the database is left without handlers. Not sure we can do anything about it since this does not relate to CGRateS but the database connection itself. We have tried in the past reporting to gorm but they told that there is not much they can do also.

DanB
