### ISSUE TITLE
Stuck call - DigiDaz

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#39]
Yesterday I had some sort of stuck call, though there were no calls showing on freeswitch one of my clients balances was continuing to deplete.

I eventually restarted cgrates, to stop the balance depleting completely. Upon reflection maybe I should have left it and then maybe I would have gotten a CDR when the balance was totally exhausted.

I couldn't really allow the balance to go to nil as this is a live client.

There is no CDR for this call so I can only guess what this clients balance should be.

I was hoping that restarting cgrates may end the calls and then rate them but this is obviously not the case as there is no CDR for it.

The client is showing about £8 of usage yesterday but his balance declined by about £50.

I thought maybe it was potentially a single long call that had had a duration of days but checking his call costs his maximum call cost since he started with us is only just over £6.

**Comment by danbogos** [comment]
Hey DigiDaz,

Interesting case you got. From what you are saying is that there could 
be some concurrency between chan_answer and chan_hangup which we use to 
start and stop debit loops but still you should get a CDR for it by the 
end of the call. If you say you did not get any CDR that is something weird.

In order to troubleshoot more, would be great if you could replicate the 
scenario and send us (could be done privately) traffic capture between 
CGRateS and FreeSWITCH (ngrep -t -W byline port 8021 -d lo) so we can 
see the order of events received. You can also capture the CDRs for such 
call with "ngrep -t -W byline port 2080 -d lo"

Looking forward for more data then.

DanB

**Comment by danbogos** [comment]
Hey DigiDaz,

Was wondering if you got any further progress with troubleshooting. I am very close to be sure that there was a concurrency issue on FS events but without traces cannot follow up much in troubleshooting.

Thanks,
DanB

**Comment by danbogos** [comment]
Hey DigiDaz,

Was there any progress on reproducing this issue? If you can confirm that it was an isolated issue and non-reproducible anymore, I would rather close the ticket and re-open it as soon as we will meet it again.

Thanks,
DanB

**Comment by DigiDaz** [comment]
Dan
 
I have never been able to reproduce this.
 
Regards
 
Darren

**Comment by danbogos** [comment]
Thanks. Will close it for now then.

DanB
