### ISSUE TITLE
[*ELS][*EES] Type casting issue

### ISSUE THREAD

**Issue by Integration-IT** [cgrates/cgrates#4228]
Hi Teams,

Actually the option store_cdrs is set to "True".
Actually the exporter is set to *els.
In fact, for the same transaction, I have 2 destinations to save and compare the same CDR.

It is possible to understand the types are not managed with the same format.

Test1: Native Cost field:
- cdrs into mongo collection : Cost type is double.
- cdrs into *els document : Cost type is string.

Test2: Extra field P-Info set to "FROM_XX" via attributes process:
- cdrs into mongo collection : extrafields object with string.
- cdrs into *els document : extrafields in root document with unknown type and an additional keyword.

Test3: Extra field ExtraSipCode with explicit casting set to 200 integer in API request side:
- cdrs into mongo collection : extrafields object with string.
- cdrs into *els document : ExtraSipCode in root document with string type.

```
...
	"ExtraDirection": "Outbound",
	"ExtraDialogReason": "Downstream BYE",
	"ExtraSipCode": 200,
	"ExtraSipReason": "OK"
}
```

Actually, it is not possible to perform efficient calculation in ELK.

[Numeric field types](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html)
[Keyword type family](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html)
[Text type family](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html)
[Object field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html)

**Comment by danbogos** [comment]
Hi @Integration-IT 

We save differently between CDRs and EEs due to the fact that in CDRs we save into a specific object (of type CDR which has particular format in CGRateS, also due to historical reasons) and in EEs exports we will send out always a hashmap (of string/string). The hashmap was decided due to generic type of fields which matches all the exporter types. I guess if a serious need arises, we can invest into adding more field types on exports.

DanB
