### ISSUE TITLE
*addons for FilterS

### ISSUE THREAD

**Issue by abdullahdhiab** [cgrates/cgrates#4235]
Hi CGRateS Team,

I'd like to know the possibility of making filter  as below:

  *lt:~*addons.<~*req.Account>.ActiveTime:+24h

addons is an external API.

appreciated,
abdullah

**Comment by danbogos** [comment]
@gezimbll, the new filter type should be named *http + MetaHashtagSep + URL and the result should be interpreted against InterfaceAsBool.
The CGREvent should be sent completely as JSON Body0 in the http request. If the Element is populated, only the Element value should be sent to the HTTP as string in the body (instead of full CGREvent). 

Sample Filters.csv:
```
#Tenant[0],ID[1],Type[2],Element[3],Values[4],ActivationInterval[5]
cgrates.org,FLTR_HTTP_FULL_EVENT,*http#http://cgrates.org/filter1,,,
cgrates.org,FLTR_HTTP_ACCOUNT_FIELD,*http#http://cgrates.org/filter1,~*req.Account,,
```

Thanks,
DanB

**Comment by abdullahdhiab** [comment]
thank you Dan.
Does it matter if the call is http or rcp? and incase i want filter to read the reply and apply like conversion on it?

**Comment by danbogos** [comment]
hi @abdullahdhiab 

It depends on what sort of rpc you are using and http is preferred due to simplicity and generality of the implementation.
You can also test is way easier (by just doing a HTTP GET towards a server). Also the implementation in the server itself should be pretty straight forward to do.

DanB

**Comment by abdullahdhiab** [comment]
@danbogos thanks Dan, much appreciated ..

**Comment by gezimbll** [comment]
Hi @abdullahdhiab  , 

The new filter type is  added on latest changes,
you can use in two ways either as  `*http#[http://server_url/endpoint]:*any:`  this  will send whole CGREvent  as json payload via a GET request,  or use as  `*http#[http://endpoint..]:~*req.Account:`, this with also be a GET request that will include  field-name and its corresponding value as query string .
For each endpoint specified  ,  we expect   a "true" or "false"  reply body with 200 status code .Look the test  as an example  https://github.com/cgrates/cgrates/blob/master/engine/filters_test.go#L2680C1-L2761C2, feel free to ask for any questions you might have.


Thanks,
Gezim

**Comment by abdullahdhiab** [comment]
thank you @gezimbll and @danbogos , i'll go through it, much appreciated.

**Comment by abdullahdhiab** [comment]
Hi @gezimbll , 
i did a test *any filter as attached but it does not send whole event as expected, with field-name it works fine.

![MMSnapshot_2024-01-21_18-13-18](https://github.com/cgrates/cgrates/assets/45718945/34af30d5-e30e-4bb8-890c-2efa67284ce4)
