### ISSUE TITLE
*addons for AttributeS

### ISSUE THREAD

**Issue by abdullahdhiab** [cgrates/cgrates#4236]
Hi CGRateS Team,

I'd like to know the possibility of making AttributeS  as below:

  *req.Subject:*variable:~*addons.<~*req.Account>.SIPStatus

addons is an external API.

appreciated,
abdullah

**Comment by danbogos** [comment]
@gezimbll,

The new Attribute Type should be  `*http + MetaHashtagSep + URL`.
The CGREvent should be sent as HTTP JSON payload and as result we can have the value we need to set at path.

Sample Attributes.csv:
```
#Tenant,ID,Contexts,FilterIDs,ActivationInterval,AttributeFilterIDs,Path,Type,Value,Blocker,Weight
cgrates.org,ATTR_HTTP,*any,*string:~*req.Account:1001,,,*req.PasswordFromHTTP,*http#http://cgrates.org/passwd,,false,10
```

Thanks,
DanB

**Comment by gezimbll** [comment]
Hi @abdullahdhiab ,

The *http attribute type is added on latest changes, 
it can be used  inline as `*http#[http://endpoint]:~*req.Category:*attributes`,it will send GET Request with the whole event as json payload .Expects  status Code 200 as reply header with  string body for populating the specified path.The "*attributes" in the end  is just placeholder without a  use case  since we are getting the value from the server.


Thanks 
Gezim

**Comment by abdullahdhiab** [comment]
thank you @gezimbll and @danbogos , i'll go through it, much appreciated.
