### ISSUE TITLE
Problem with recurring action triggers

### ISSUE THREAD

**Issue by DigiDaz** [cgrates/cgrates#462]
After creating a recurring action trigger for example a balance alert, once the threshold has been crossed, the trigger seems to get fired everytime a debit to the account occurs. Once debits stop, the trigger stops firing until debits start again.

DanB says this is due to: lastExecutedTime is not being saved in the db,

**Comment by ewsamuels** [comment]
I can also confirm this is the case with my tests.

**Comment by ewsamuels** [comment]
Here are the steps we use to create the Balance Alerts

### 1. Setup Trigger for Alerts

curl -X POST -H "Content-Type: application/json" -d '{"method": "ApierV1.SetActions", "params": [{"ActionsId": "BALANCE_ALERT", "Overwrite": true, "Actions": [{"ExtraParameters": "http://cgrates.org:/balance_alert/", "Identifier": "*call_url_async", "BalanceId": "*default", "BalanceWeight": "0", "Directions": "*out", "Units":"0", "Weight": 10, "ExpiryTime": "*unlimited", "BalanceType": "*monetary"}]}]}' http://localhost:2080/jsonrpc

### 2. Add a Global Default Action Trigger
#### a) First check if any ActionTriggers have been created

curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetActionTriggers","params":[{"GroupIDs": ["BAL_ALERT_TRIGGERS"]}]}' http://localhost:2080/jsonrpc

If any results are returned we need to delete any existing ActionTriggers

>> At the time of writing there is no API for removing ActionTriggers so we need to remove them directly from Redis

#### b) Set a Global ActionTrigger with default ThresholdValue and Minsleep.
**Here I am setting the default to 10 years since our default Frequency is Never**

curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.SetActionTrigger", "params": [{"GroupID": "BAL_ALERT_TRIGGERS", "ThresholdType": "*min_balance", "ThresholdValue": 0, "Recurrent": true, "MinSleep": "87600h", "BalanceType":"*monetary", "ActionsID": "BALANCE_ALERT"}]}' http://localhost:2080/jsonrpc

### 3. Setup Alert Trigger for a specific Account
#### a) First Check if any Account Action Triggers already exists
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetAccountActionTriggers","params":[{"Tenant":"cgrates.org","Account":"1480270993"}]}' http://localhost:2080/jsonrpc

{
  "id": null,
  "result": [
    {
      "ID": "BAL_ALERT_TRIGGERS",
      "UniqueID": "d4c69ed2-43cb-46e4-a7c8-951335a15190",
      "ThresholdType": "*min_balance",
      "ThresholdValue": 50,
      "Recurrent": true,
      "MinSleep": 21600000000000,
      "ExpirationDate": "0001-01-01T00:00:00Z",
      "ActivationDate": "0001-01-01T00:00:00Z",
      "Balance": {
        "Uuid": null,
        "ID": null,
        "Type": "*monetary",
        "Value": null,
        "Directions": null,
        "ExpirationDate": null,
        "Weight": null,
        "DestinationIDs": null,
        "RatingSubject": null,
        "Categories": null,
        "SharedGroups": null,
        "TimingIDs": null,
        "Timings": null,
        "Disabled": null,
        "Factor": null,
        "Blocker": null
      },
      "Weight": 0,
      "ActionsID": "BALANCE_ALERT",
      "MinQueuedItems": 0,
      "Executed": false
    }
  ],
  "error": null
}
#### b) Remove existing RemAccountActionTriggers
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.RemoveAccountActionTriggers","params":[{"GroupID":"BAL_ALERT_TRIGGERS","Tenant":"cgrates.org","Account":"1480270993"}]}' http://localhost:2080/jsonrpc
{"id":null,"result":"OK","error":null}

#### c) Now Add the Default Action Account Trigger to the specific Account
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.AddAccountActionTriggers", "params": [{"Tenant": "cgrates.org", "Account": "1480270993", "ActionTriggerIDs": ["BAL_ALERT_TRIGGERS"], "ActionTriggerOverwrite": true}]}' http://localhost:2080/jsonrpc


#### d) Now Check the Account Action Trigger again
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.GetAccountActionTriggers","params":[{"Tenant":"cgrates.org","Account":"1480270993"}]}' http://localhost:2080/jsonrpc

### Step 4. Now Modify the AccountActionTrigger for a specifc Account with ThresholdValue etc
curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.SetAccountActionTriggers", "params": [{"Tenant": "cgrates.org", "Account": "1480270993", "GroupID": "BAL_ALERT_TRIGGERS", "ThresholdType": "*min_balance", "ThresholdValue": 25, "Recurrent": true, "MinSleep": "5m", "BalanceType":"*monetary", "ActionsID": "BALANCE_ALERT"}]}' http://localhost:2080/jsonrpc

### Step 5. Test the alert is working

curl -X POST -H "Content-Type: application/json" -d '{"method":"ApierV1.ExecuteAction","params":[{"Tenant":"cgrates.org","Account":"1480270993","ActionsId":"BALANCE_ALERT"}]}' http://localhost:2080/jsonrpc

So with this setup we only get alerts during a live call and the alerts are sent everytime the account is debited until the call is hung up.

root@cgrates:~# ls -l /usr/bin | grep cgr
-rwxr-xr-x 1 root   root    14462784 May 11 14:38 cgr-console
-rwxr-xr-x 1 root   root    20186080 May 11 14:38 cgr-engine
-rwxr-xr-x 1 root   root    15519456 May 11 14:38 cgr-loader
-rwxr-xr-x 1 root   root    14663360 May 11 14:38 cgr-tester

**Comment by rif** [comment]
I closed the ticket from the commit message. Please test and reopen if not fixed.
