### ISSUE TITLE
add account ID in action_trigger_logs

### ISSUE THREAD

**Issue by simon-af** [cgrates/cgrates#471]
Hi,

Is it possible to add the ID of account in "action_trigger_logs" collection (storDB)?

Thanks.

**Comment by danbogos** [comment]
Hey @simon-af ,

We need to find another approach to action_trigger_logs since based on our internal evaluation they are a serious performance leak. They were there from starting of the project and honestly we kinda forgot about them.
Will need to completely take these logs out and if you cannot live without them maybe use pubsubs with events logged by another component (maybe your http server) if really needed.

DanB
