### ISSUE TITLE
Duplicate entry in Destinations causes no data storage in StorDB

### ISSUE THREAD

**Issue by marcinkowalczyk** [cgrates/cgrates#475]
Hi,
I've just noticed, that there is an issue while loading data using cgr-loader and import_tp_from_folder. When there is duplication in destinations data will be loaded into Redis but it fails to load into StorDB. 

Way to reproduce issue:
Put following into Destinations.csv:
# Tag,Prefix

Portugal_Meo_Mobile,3511696
Portugal_Meo_Mobile,3511696
Portugal_Meo_Mobile,3511896
Portugal_Meo_Mobile,3511896

redis will be populated, but StorDB will be empty. 

Both cgr-loader and cgr-console reports OK on finish.

**Comment by danbogos** [comment]
Hi @marcinkowalczyk 

What StorDB type are you using?

Thanks,
DanB

**Comment by marcinkowalczyk** [comment]
Hi, 


I'm using MySQL 5.5. When  tracing traffic on 3306 I can see constraint error key duplication. This causes transaction rollback triggered by client (CGRateS). 

I've tried on rc8 master build from mid April and 17.06. Removing duplicate fixes issue. 





On Tue, Jun 21, 2016 at 11:20 PM +0200, "Dan Christian Bogos" <notifications@github.com> wrote:












Hi @marcinkowalczyk 



What StorDB type are you using?



Thanks,

DanB

**Comment by danbogos** [comment]
Hi @marcinkowalczyk 

Just to make it clear, can u reproduce the issue with latest package (17.06)?

Thanks,
DanB

**Comment by marcinkowalczyk** [comment]
Correct

**Comment by danbogos** [comment]
OK. Will try to replicate here and come back to you.

Please note that being holiday season here, it might bring up some delays in solving this issue.

Ta,
DanB

**Comment by danbogos** [comment]
hi @marcinkowalczyk 

We have checked the issue and it shows up due to duplicate records protection in StorDB. We use transactions there and that is the reason your records will not show up inside. In case of DataDB, we will compile things in memory and eliminate duplicates ourselves. 
The different behavior is also expected since in case of StorDB we import 1-1 and in case of DataDB we compile into internal objects.
I think at least for the moment we will leave the duplicate checks mechanism preventing us inserting records in order to reduce the garbage we insert into StorDB.

Thanks,
DanB
