### ISSUE TITLE
MediatorV1.RateCdrs issue

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#48]
Hello,
There seems to be an issue when I ReRate CDRs the account balances are not correctly adjusted it seems that the existing balance just increases by the value of the CDRs that were ReRated which is incorrect.  Or maybe I did something wrong, here is the API call I did.
```
response = connection.call("MediatorV1.RateCdrs",{"Tenant":"cgrates.org","TimeStart":"2015-03-01T00:00:00Z","TimeEnd":"2015-03-07T00:00:00Z","RerateErrors":True,"RerateRated":True})
```
How do I reset the Balance or correctly adjust the balance?
regards,

Errol

**Comment by danbogos** [comment]
Hi Errol,

The re-rate cdrs will process balances as during the call, so if you run it on accounts related, you can get double balance debit-ed. This API should run more on errors so not really on prepaid/postpaid calls which were previously rated.

You should make sure you run it with RerateRated: false in case of "pseudoprepaid", "prepaid" and "postpaid" ReqTypes. In case of "rated" you can do RerateRated also since that type has nothing to do with balances.

The reason we don't process balances is because of complexity of giving back what we have initially taken since the debits are time related and involve other variables (like special offers, bonuses and such).

Regarding resetting Balances, you will need to do it manually via cgr-console, API or .csv files since there is no automated way developed.

From our point of view this is not an issue so will close the ticket for now.

DanB

**Comment by ewsamuels** [comment]
DanB, just for the record the reason why I needed to rerate already rated CDRs is because there were a few thousand CDRs that were rated with the incorrect rate.  For example there were rated at $1.25 per minute instead of 0.0125 (1.25 cents per minute).

**Comment by danbogos** [comment]
I get it, was there something CGR related (the wrong rating)?

DanB
