### ISSUE TITLE
RunFilter in Derived Chargers 

### ISSUE THREAD

**Issue by grencik** [cgrates/cgrates#545]
Hi,
I'd like to ask how to use RunFilters in Derived Charges. As far as I can understand regular expression match over RunFilters column is performed over a result out of redisDB. I have found an example [here](https://github.com/cgrates/cgrates/blob/25c61b7d650f009f0b91f9408991bff43a5a65c7/utils/derivedchargers_test.go#L75) but this didn't work in my case.

Is my assumption correct?
Is the syntax ^<match_column>/<match_value>/   ?
Can I use cdr_extra data in match_column?

Thanks

Robert

**Comment by danbogos** [comment]
Hi @grencik 

You should use RSR fields as filters there. You can find some basic documentation here:
http://cgrates.readthedocs.io/en/latest/cdrclient.html#cgr-rsr-regexp-rule
Extra to what is in that page is that you will provide the filter value at the end of the format, between ().

Some examples in tests:

 * Build an RSR with filter:
https://github.com/cgrates/cgrates/blob/master/utils/rsrfield_test.go#L191

 * Various filter possibilities:
https://github.com/cgrates/cgrates/blob/master/utils/rsrfield_test.go#L236

If this info is not clear enough, please let  me know the complete logic of filtering you need and I will build a sample which could help faster understanding.

DanB

PS: Please note that we tend to keep issues here on github for real issues with the software like bug or feature requests and for general questions we recommend google group CGRateS or IRC (#cgrates on freenode) since there can be more people benefiting of the solutions given.

**Comment by grencik** [comment]
Hi @danbogos,

thank you very much, it works like a charm :)

Robert

**Comment by danbogos** [comment]
Sure, just keep in mind that the field filters are faster than RSR rules (they need to be compiled on each CDR).

DanB
