### ISSUE TITLE
ApierV1.DebitUsage doesn't honor AllowNegative setting on account

### ISSUE THREAD

**Issue by shaneneuerburg** [cgrates/cgrates#568]
If the account is set up to not allow negative balances, and DebitUsage is called with data that results in a cost greater than the balance, the balance ends up going negative.

From my limited knowledge of the code base, it appears that DebitUsage ends up in calldesc.go's `Debit()` method via responder.go. That method ends up calling the `Debit(...)` method with parameters, one being an allowNegative parameter. `Debit()` sends in `true`, which overrides the account's allowNegative setting.

**Comment by danbogos** [comment]
Right now it behaves as originally planned since Debit was supposed to be called only at the end of the usage (there is no revert to Debit). We could come up with a parameter preventing debit to happen if allowNegative is set. The answer should be error in that case and the original debit should be canceled.
Will put it on wishlist for now.

DanB

**Comment by danbogos** [comment]
Should be fixed in master, together with integrating PR.

DanB
