### ISSUE TITLE
LoadTariffPlanFromStorDb Performance

### ISSUE THREAD

**Issue by ewsamuels** [cgrates/cgrates#58]
Hi DanB,

I was finally able to test this from clean install using the package dated 9th April but the results are not very consistent.
I tested this a few times and on average it took approximately 20 minutes to complete. The second time it took about 41 mins to complete and the third time it took approximately 1 hour and 30 mins.

Each time I used exactly the same parameters:
connection.call("ApierV1.LoadTariffPlanFromStorDb", {"TPid":"TARIFFPLAN1", "FlushDb":False, "DryRun":False})

Anyway, I am not sure which method you are using to do inserts into Redis but I saw an interesting post about doing Mass Insertion in Redis which might be useful to you here: http://redis.io/topics/mass-insert

Regards,

Errol

**Comment by danbogos** [comment]
Hi Errol

Thanks for your tests. Can u compare this new method with load from .csv in
terms of speed for the same data?

DanB
Am 11.04.2015 12:41 schrieb "ewsamuels" <notifications@github.com>:

**Comment by danbogos** [comment]
Following up IRC, we got about 10 minutes for loading Destinations.csv. Both methods (from .csv or Postgres) should return more or less the same time.

For the moment this is considered as normal since we only compile the tariff plan once on load and after reaches dataDb will be loaded in seconds from it every time we re-cache.

DanB
