### ISSUE TITLE
ApierV1.AddBalance doesn't save DestinationIDs if account already exists

### ISSUE THREAD

**Issue by MrGab** [cgrates/cgrates#585]
if you add balance through api, the balance is correctly added but DestinationIDs are not saved if the account already exists.
Scenario to reproduce the issue:
- Create a new Account via ApierV1.SetAccount
- Add voice balance with DirectionIDs via ApierV1.AddBalance
- Get account via ApierV2.GetAccount
Below the ngrep output:
http://pastebin.com/4y4XWEgj

Scenario that saves correctly DestinationIDs
- Add voice balance with DirectionIDs via ApierV1.AddBalance for an account not already present
- Get Account via ApierV2.GetAccount
Below the ngrep output:
http://pastebin.com/1Fyxd5L3

**Comment by danbogos** [comment]
Hi @MrGab 

Have checked and AddBalance is not supposed to add balance in the way you expect it. If you need to create a new balance, you should use SetBalance since that considers also the filters. AddBalance is supposed to just add value and the rest are used as filters to match the right balance, without explicitly setting them.
If SetBalance does not work for you, please let me know and I will reconsider it, maybe extend AddBalance, however I prefer avoiding that since I don't know how many people expect it to work already in that way (old behavior).

Thanks,
DanB

**Comment by danbogos** [comment]
Closing due to no response in the last 10 days.
Please re-open if the issue occurs again.

DanB
