### ISSUE TITLE
Using Postgres instead of redis

### ISSUE THREAD

**Issue by nbhatti** [cgrates/cgrates#59]
How can I use Posrgres to import rates rather than use redis for everything? I see the source has been changed a lot recently but the documentation lacks behind a lot. Specially the config files.

**Comment by danbogos** [comment]
Hi @nbhatti,
Postgres implementation was only meant to cover storDb (offline storage) part of CGRateS storage. For dataDb (live one) the only option right now is Redis (for performance considerations).
The documentation still follows the latest release (rc5) which did not include postgres support and was configured via .cfg file instead of the new .json format. If you are looking to test the master, I recommend to follow the tutorial which should be up to date in terms of both documentation and configuration necessary.

Hope this helps,
DanB
