### ISSUE TITLE
issue with balances

### ISSUE THREAD

**Issue by miha-** [cgrates/cgrates#685]
Hello

Actions.csv
ROAM,*topup_reset,"{""*data"":1024.0}",,DATA_SLO,*data,*out,*any,*any,balance-slovenia,,*unlimited,,15000,10,false,false,10

RatingProfiles.csv
*out,softnet-mobil,home-data,balance-slovenia,2016-08-01T00:00:00Z,RP_SLO_VOICE_FREE,,
*out,softnet-mobil,eu-data,balance-slovenia,2016-08-01T00:00:00Z,RP_SLO_DATA_ZAMLADE,,

csv:
{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params": [{"Direction":"*out","cgrid":"4","Category":"eu-data","RequestType":"*postpaid","ToR":"*data","Tenant":"softnet-mobil","Account":"386513123213","Destination":"38611111","Subject":"balance-slovenia","AnswerTime":"2016-12-03T13:00:00Z","Usage":"5120000"}]}

[
 {
  "ID": "softnet-mobil:38651357952",
  "BalanceMap": {
   "*data": [
    {
     "Uuid": "7797febc-0dd9-4ac4-b75f-53a808a56bec",
     "ID": "DATA_SLO",
     "Value": 15000,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": "0001-01-01T00:00:00Z",
     "Weight": 10,
     "DestinationIDs": {},
     "RatingSubject": "balance-slovenia",
     "Categories": {},
     "SharedGroups": {},
     "Timings": null,
     "TimingIDs": {},
     "Disabled": false,
     "Factor": {
      "*data": 1024
     },
     "Blocker": false
    }
   ]
  },
  "UnitCounters": null,
  "ActionTriggers": [
   {
    "ID": "BALANCE_TRIGGER_PREMIUM_DATA",
    "UniqueID": "eff6c422-aa6c-4ae4-8e49-be8731b09868",
    "ThresholdType": "*min_balance",
    "ThresholdValue": 2048,
    "Recurrent": false,
    "MinSleep": 0,
    "ExpirationDate": "0001-01-01T00:00:00Z",
    "ActivationDate": "0001-01-01T00:00:00Z",
    "Balance": {
     "Uuid": null,
     "ID": null,
     "Type": "*data",
     "Value": null,
     "Directions": {
      "*out": true
     },
     "ExpirationDate": null,
     "Weight": null,
     "DestinationIDs": null,
     "RatingSubject": null,
     "Categories": null,
     "SharedGroups": null,
     "TimingIDs": null,
     "Timings": null,
     "Disabled": null,
     "Factor": null,
     "Blocker": null
    },
    "Weight": 10,
    "ActionsID": "LOG_POST",
    "MinQueuedItems": 0,
    "Executed": false,
    "LastExecutionTime": "0001-01-01T00:00:00Z"
   }
  ],
  "AllowNegative": false,
  "Disabled": false
 }
]

cdr:

{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params": [{"Direction":"*out","cgrid":"4","Category":"eu-data","RequestType":"*postpaid","ToR":"*data","Tenant":"softnet-mobil","Account":"38651357952","Destination":"3861357952","Subject":"balance-slovenia","AnswerTime":"2016-12-03T13:00:00Z","Usage":"5120000"}]}

log from mysql:

{"Tenant":"softnet-mobil","ID":"38651357952","BalanceSummaries":[{"ID":"DATA_SLO","Type":"*data","Value":15000,"Disabled":false},{"ID":"*default","Type":"*monetary","Value":-204.99999998709671,"Disabled":false}],"AllowNegative":false,"Disabled":false}

{"Direction":"*out","Category":"eu-data","Tenant":"softnet-mobil","Subject":"balance-slovenia","Account":"38651357952","Destination":"3861357952","TOR":"*data","Cost":205,"Timespans":[{"TimeStart":"2016-12-03T13:00:00Z","TimeEnd":"2017-01-31T19:13:20Z","Cost":205,"RateInterval":{"Timing":{"Years":[],"Months":[],"MonthDays":[],"WeekDays":[],"StartTime":"00:00:00","EndTime":""},"Rating":{"ConnectFee":0,"RoundingMethod":"*up","RoundingDecimals":4,"MaxCost":0,"MaxCostStrategy":"","Rates":[{"GroupIntervalStart":0,"Value":0.041,"RateIncrement":1000000000,"RateUnit":1024000000000}]},"Weight":10},"DurationIndex":5120000000000000,"Increments":[{"Duration":1000000000,"Cost":4.00390625e-05,"BalanceInfo":{"Unit":null,"Monetary":{"UUID":"0819dfa6-93d4-4406-93e0-cb254b55eaa9","ID":"*default","Value":-204.99999998709671,"RateInterval":null},"AccountID":"softnet-mobil:38651357952"},"CompressFactor":5120000}],"RoundIncrement":null,"MatchedSubject":"*out:softnet-mobil:eu-data:balance-slovenia","MatchedPrefix":"*any","MatchedDestId":"*any","RatingPlanId":"RP_SLO_DATA_ZAMLADE","CompressFactor":1}],"RatedUsage":5.12e+06}

If I use category "eu-data"  balance is not deducted, but it is only charged. If I use home-data as category then balance is deducted but balance should be mached and deducted. If anything else is needed please let me know. I also tried with *voice balance but it is the same issue.

tnx
miha

**Comment by danbogos** [comment]
Hi Miha

please attach also few lines (max 3 of each) for RatingPlans.csv
DestinationRates.csv and Rates.csv which I can use to rate your CDR.

Ta
DanB

Am 29.06.2017 08:07 schrieb "miha-" <notifications@github.com>:

Hello

Actions.csv
ROAM,*topup_reset,"{""*data"":1024.0}",,DATA_SLO,*data,*out,
*any,*any,balance-slovenia,,*unlimited,,15000,10,false,false,10

RatingProfiles.csv
*out,softnet-mobil,home-data,balance-slovenia,2016-08-
01T00:00:00Z,RP_SLO_VOICE_FREE,,
*out,softnet-mobil,eu-data,balance-slovenia,2016-08-
01T00:00:00Z,RP_SLO_DATA_ZAMLADE,,

csv:
{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params":
[{"Direction":"*out","cgrid":"4","Category":"eu-data","
RequestType":"*postpaid","ToR":"*data","Tenant":"softnet-mobil","Account":"
386513123213","Destination":"38611111","Subject":"balance-
slovenia","AnswerTime":"2016-12-03T13:00:00Z","Usage":"5120000"}]}

[
{
"ID": "softnet-mobil:38651357952",
"BalanceMap": {
"*data": [
{
"Uuid": "7797febc-0dd9-4ac4-b75f-53a808a56bec",
"ID": "DATA_SLO",
"Value": 15000,
"Directions": {
"*out": true
},
"ExpirationDate": "0001-01-01T00:00:00Z",
"Weight": 10,
"DestinationIDs": {},
"RatingSubject": "balance-slovenia",
"Categories": {},
"SharedGroups": {},
"Timings": null,
"TimingIDs": {},
"Disabled": false,
"Factor": {
"*data": 1024
},
"Blocker": false
}
]
},
"UnitCounters": null,
"ActionTriggers": [
{
"ID": "BALANCE_TRIGGER_PREMIUM_DATA",
"UniqueID": "eff6c422-aa6c-4ae4-8e49-be8731b09868",
"ThresholdType": "*min_balance",
"ThresholdValue": 2048,
"Recurrent": false,
"MinSleep": 0,
"ExpirationDate": "0001-01-01T00:00:00Z",
"ActivationDate": "0001-01-01T00:00:00Z",
"Balance": {
"Uuid": null,
"ID": null,
"Type": "*data",
"Value": null,
"Directions": {
"*out": true
},
"ExpirationDate": null,
"Weight": null,
"DestinationIDs": null,
"RatingSubject": null,
"Categories": null,
"SharedGroups": null,
"TimingIDs": null,
"Timings": null,
"Disabled": null,
"Factor": null,
"Blocker": null
},
"Weight": 10,
"ActionsID": "LOG_POST",
"MinQueuedItems": 0,
"Executed": false,
"LastExecutionTime": "0001-01-01T00:00:00Z"
}
],
"AllowNegative": false,
"Disabled": false
}
]

cdr:

{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params":
[{"Direction":"*out","cgrid":"4","Category":"eu-data","
RequestType":"*postpaid","ToR":"*data","Tenant":"softnet-
mobil","Account":"38651357952","Destination":"3861357952","
Subject":"balance-slovenia","AnswerTime":"2016-12-03T13:00:
00Z","Usage":"5120000"}]}

log from mysql:

{"Tenant":"softnet-mobil","ID":"38651357952","BalanceSummaries":[{"ID":"
DATA_SLO","Type":"*data","Value":15000,"Disabled":false}
,{"ID":"*default","Type":"*monetary","Value":-204.99999998709671,"Disabled":
false}],"AllowNegative":false,"Disabled":false}

{"Direction":"*out","Category":"eu-data","Tenant":"softnet-
mobil","Subject":"balance-slovenia","Account":"38651357952","Destination":"
3861357952","TOR":"*data","Cost":205,"Timespans":[{"
TimeStart":"2016-12-03T13:00:00Z","TimeEnd":"2017-01-31T19:
13:20Z","Cost":205,"RateInterval":{"Timing":{"Years":[],"Months":[],"
MonthDays":[],"WeekDays":[],"StartTime":"00:00:00","EndTime":""},"Rating":{"
ConnectFee":0,"RoundingMethod":"*up","RoundingDecimals":4,"
MaxCost":0,"MaxCostStrategy":"","Rates":[{"GroupIntervalStart":0,"Value":
0.041,"RateIncrement":1000000000,"RateUnit":1024000000000}]},"Weight":10},
"DurationIndex":5120000000000000,"Increments":[{"Duration":1000000000,"Cost"
:4.00390625e-05,"BalanceInfo":{"Unit":null,"Monetary":{"
UUID":"0819dfa6-93d4-4406-93e0-cb254b55eaa9","ID":"*default","Value":-204.
99999998709671,"RateInterval":null},"AccountID":"softnet-
mobil:38651357952"},"CompressFactor":5120000}],"RoundIncrement":null,"
MatchedSubject":"*out:softnet-mobil:eu-data:balance-
slovenia","MatchedPrefix":"*any","MatchedDestId":"*any","
RatingPlanId":"RP_SLO_DATA_ZAMLADE","CompressFactor":1}],
"RatedUsage":5.12e+06}

If I use category "eu-data" balance is not deducted, but it is only
charged. If I use home-data as category then balance is deducted but
balance should be mached and deducted. If anything else is needed please
let me know. I also tried with *voice balance but it is the same issue.

tnx
miha

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cgrates/cgrates/issues/685>, or mute the thread

**Comment by miha-** [comment]
Hello Dan

RatingProfiles.csv
#ROAM
*out,softnet-mobil,eu-data,balance-slovenia,2016-08-01T00:00:00Z,RP_SLO_DATA_ZAMLADE,,
*out,softnet-mobil,eu-data,*any,2016-08-01T00:00:00Z,RP_SLO_DATA,,

DestinationRates.csv
DR_SLO_DATA_ZAMLADE,*any,RT_SLO_DATA_ZAMLADE,*up,4,0,
DR_SLO_DATA,*any,RT_SLO_DATA,*up,4,0,

Rates.csv
RT_SLO_DATA_ZAMLADE,0,0.0410,1024,1,0
RT_SLO_DATA,0,0.1311,1024,1,0


RatingPlans.csv
RP_SLO_DATA_ZAMLADE,DR_SLO_DATA_ZAMLADE,*any,10
RP_SLO_DATA,DR_SLO_DATA,*any,10


Pleasse let me know if anything else is needed.

tnx
miha

**Comment by danbogos** [comment]
hi @miha- 

I am back ;).

It appears the bug comes from default *monetary balance missing. Can you maybe try creating it when you create the *data one and repost your findings?

Ta,
DanB

PS: Factor parameter is only used for *generic type so you don't need to use it for any other tor. One other thing I have noted is that you are posting subject, but no need for that since it will be taken from the balance rating subject.

**Comment by miha-** [comment]
Hey Dan

i create ti like this:

ROAM,*topup_reset,"{""*data"":1024.0}",,DATA_SLO,*data,*out,*any,*any,balance-slovenia,,*unlimited,,15000,10,false,false,10
ROAM,*topup_reset,"{""*data"":1024.0}",,DATA_EU,*data,*out,eu-data,*any,,,*unlimited,,5000,20,false,false,10
ROAM,*topup_reset,,,*default,*monetary,,,,,,*unlimited,,0,10,false,false,10

But I am having still the same issue.


Tnx for helping.
miha

**Comment by danbogos** [comment]
You need one *monetary.

DanB

Am 03.07.2017 07:53 schrieb "miha-" <notifications@github.com>:

**Comment by miha-** [comment]
Hello Dan

i noticed one thing.

In case of this cdr:

{"id": "1", "method": "CdrsV1.ProcessExternalCDR", "params":
[{"Direction":"*out","cgrid":"4","Category":"eu-data","
RequestType":"*postpaid","ToR":"*data","Tenant":"softnet-
mobil","Account":"38651357952","Destination":"3861357952","
Subject":"balance-slovenia","AnswerTime":"2016-12-03T13:00:
00Z","Usage":"5120000"}]}

it is ok, but when you change category to "home-data", it does not calculate monetary part when balance reach "0", so the same issue as before for eu-data. When you put *monetary balance to some value (10000) it is ok till when it reach 0 balance.


tnx
miha
