### ISSUE TITLE
TPAliases struct inconsistency

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#708]
Hi,
ApierV1.RemTPAlias is resulting with error": "SERVER_ERROR: not found", when ApierV1.GetTPAlias works OK.

I think there is a mistake, at
https://github.com/cgrates/cgrates/blob/2d0146d4960f894b5a999bb793f5dcab1f939cb9/apier/v1/tpaliases.go#L26
checking for "Group" field when TPAliases struct has "Context" field.
That is somehow mixes the data making it impossible to delete TPAliases objects.

Thanks,

**Comment by danbogos** [comment]
Hi @muxalko 

Thanks for reporting!

Since the TPAliases will change in structure over the next couple of weeks, we will be handling this ticket after the changes. 
I cannot tell for sure whether you have a real issue before finishing with the changes since it will be double work here. I will update the issue as soon as we are ready with the changes which I am sure it will be an advantage for both of us.

Thanks again!

DanB

**Comment by danbogos** [comment]
This issue should be fixed by replacing aliases with attributes.

DanB
