### ISSUE TITLE
problem with detection of new version schema

### ISSUE THREAD

**Issue by linuxmaniac** [cgrates/cgrates#750]
We have this schema version info in REDIS (**data_db**):
```
127.0.0.1:6379[10]> get ver_struct
"\xde\x00\x12\xa8Accounts\xa11\xabActionPlans\xa11\xaeActionTriggers\xa11\xa7Actions\xa11\xa5Alias\xa11\xa8CdrStats\xa11\xa4Cdrs\xa11\xafDerivedChargers\xa11\xacDestinations\xa11\xa4Lcrs\xa11\xabLoadHistory\xa11\xa7PubSubs\xa11\xabRatingPlans\xa11\xaeRatingProfiles\xa11\xaeResourceLimits\xa11\xa7SMCosts\xa11\xacSharedGroups\xa11\xa5Users\xa11"
```
But ``cgr-engine`` doesn't detect that the schema is old, it just writes the new values

```
127.0.0.1:6379[10]> HGETALL versions
 1) "Actions"
 2) "2"
 3) "ActionTriggers"
 4) "2"
 5) "ActionPlans"
 6) "2"
 7) "SharedGroups"
 8) "2"
 9) "Accounts"
10) "2"
```
Is worst for Postgresql (**stor_db**), not having even the ``versions`` table it just complains but doesn't stop the process.

```
(pq: relation "versions" does not exist) 
[2017-09-22 12:46:22]  
```

**Comment by danbogos** [comment]
Hi @linuxmaniac 

We have changed the way we store versions, so you will need to create new structures.

To fix it in dataDB, just run "cgr-migrator -migrate=*set_versions".
For Postgres you need to create the table yourself manually from here:
https://github.com/cgrates/cgrates/blob/master/data/storage/postgres/create_tariffplan_tables.sql#L475

The reason Postgres is not integrated in migrator is because schema being created via setup script. When migrating from rc7 we do it via another script, 
https://github.com/cgrates/cgrates/blob/master/data/storage/migrator/rc7_to_rc8.sh

Let us know if any issue.

DanB

**Comment by linuxmaniac** [comment]
With my changes:

* when old schema is in place:
```
127.0.0.1:6379[10]> set ver_struct whatever
OK
```
```
# ~/.go/bin/cgr-engine -log_level 7 
old schema detected. Migration needed, use cgr-migrator
```
* when db schema has no versions table:
```
127.0.0.1:6379[10]> del ver_struct
(integer) 1
```
```
# ~/.go/bin/cgr-engine -log_level 7                                                                 
Could not get schema versions: pq: relation "versions" does not exist
```
and redis schema is set as expected:
```
127.0.0.1:6379[10]> hgetall versions
 1) "SharedGroups"
 2) "2"
 3) "Accounts"
 4) "2"
 5) "Actions"
 6) "2"
 7) "ActionTriggers"
 8) "2"
 9) "ActionPlans"
10) "2"
```
```
CREATE TABLE versions (
  "id" SERIAL PRIMARY KEY,
  "item" varchar(64) NOT NULL,
  "version" INTEGER NOT NULL,
  UNIQUE (item)
);
```
REDIS and postgres schemas in place:
```
# ~/.go/bin/cgr-engine -log_level 7 
2017/09/23 08:48:53 method Call has wrong number of ins: 4
2017/09/23 08:48:53 method Call has wrong number of ins: 4
2017/09/23 08:48:53 method ProcessExternalCdr has wrong number of ins: 2
2017/09/23 08:48:53 method RateCDRs reply type not a pointer: bool
2017/09/23 08:48:53 method RegisterHandlersToServer has wrong number of ins: 2
2017/09/23 08:48:53 method Timezone has wrong number of ins: 1

```
So now cgr-engine doesn't start if any schema is wrong as expected

**Comment by danbogos** [comment]
Hey @linuxmaniac,

if you like to fix it whithin CGR, use the non empty database query, ie if
any key in redis and versions not present or lower than needed, migration
error should occur. We set versions only if no data in database.

If you implement it in this way, please send a PR if you like to contribute.

Thanks,
DanB

Am 23.09.2017 09:50 schrieb "Victor Seva" <notifications@github.com>:

With my changes:

   - when old schema is in place:

127.0.0.1:6379[10]> set ver_struct whatever
OK

# ~/.go/bin/cgr-engine -log_level 7
old schema detected. Migration needed, use cgr-migrator


   - when db schema has no versions table:

127.0.0.1:6379[10]> del ver_struct
(integer) 1

# ~/.go/bin/cgr-engine -log_level 7
Could not get schema versions: pq: relation "versions" does not exist

and redis schema is set as expected:

127.0.0.1:6379[10]> hgetall versions
 1) "SharedGroups"
 2) "2"
 3) "Accounts"
 4) "2"
 5) "Actions"
 6) "2"
 7) "ActionTriggers"
 8) "2"
 9) "ActionPlans"
10) "2"

CREATE TABLE versions (
  "id" SERIAL PRIMARY KEY,
  "item" varchar(64) NOT NULL,
  "version" INTEGER NOT NULL,
  UNIQUE (item)
);

REDIS and postgres schemas in place:

# ~/.go/bin/cgr-engine -log_level 7
2017/09/23 08:48:53 method Call has wrong number of ins: 4
2017/09/23 08:48:53 method Call has wrong number of ins: 4
2017/09/23 08:48:53 method ProcessExternalCdr has wrong number of ins: 2
2017/09/23 08:48:53 method RateCDRs reply type not a pointer: bool
2017/09/23 08:48:53 method RegisterHandlersToServer has wrong number of ins: 2
2017/09/23 08:48:53 method Timezone has wrong number of ins: 1


So now cgr-engine doesn't start if any schema is wrong as expected

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cgrates/cgrates/issues/750#issuecomment-331618063>, or mute
the thread

**Comment by linuxmaniac** [comment]
> if you like to fix it whithin CGR, use the non empty database query, ie if
> any key in redis and versions not present or lower than needed, migration
> error should occur. We set versions only if no data in database.

I don't get what you mean. Can you, please, rephrase.
