### ISSUE TITLE
*data balance issue

### ISSUE THREAD

**Issue by muxalko** [cgrates/cgrates#840]
Hello Dear CGRateS Team!

When trying latest master commit, there was an issue with *data balance.
Even when it is present in account BalanceMap, rater is ignoring it.
Charging *monetary balance is OK.

Please find attached,
TP:
[TP_Prepaid_Data_Issue.zip](https://github.com/cgrates/cgrates/files/1506429/TP_Prepaid_Data_Issue.zip)
Traces:
[ChargingSession.txt](https://github.com/cgrates/cgrates/files/1506388/ChargingSession.txt)
[Account.txt](https://github.com/cgrates/cgrates/files/1506389/Account.txt)
[CDR.txt](https://github.com/cgrates/cgrates/files/1506390/CDR.txt)

Thanks,
Michael

**Comment by muxalko** [comment]
Hello Dan,
Still can't understand what is wrong here. Is that only me having this weird problem.
I mean, it's pretty basic stuff, if there were any issues with the code, you would had caught it with test.

Can I run tests in my environment for the usage balances?

Thanks,
Michael

**Comment by danbogos** [comment]
Hey Michael,

I tried to replicate your setup but I am a bit confused by the number of accounts (none matching the account sample you attached here) and not sure whether the data is the right one to replicate your issue.

Can you please add only the relevant information here? I would need only one account to be created (the one which replicates your problem). Also your part of debug (account and CDR) should be based on exactly same data (same account)?

If I don't get the same information as you, it will be difficult to troubleshoot not knowing whether the cause comes from misunderstanding of info or it is really in the code.

Ta,
DanB

**Comment by muxalko** [comment]
Hello Dan,
Sorry, but, I am not following, the account used in the example is golant:972536213067, and is the only used one. It appears in Account dump and CDR, as well as data charging flow captured with ngrep.
Perhaps, that is exactly the issue here ? 
What is not matching ?


Thanks,
Michael

**Comment by danbogos** [comment]
Hey Michael,

Sorry, for some reason I was using before some wrong data (could have been stale from previous tests I did for you).
I was able to replicate now your issue and will come back to you asap.

DanB

**Comment by danbogos** [comment]
Hey Michael,

The issue was in the way you have defined RatingSubject (*zero102400). We have still expected time unit in the end (ie: *zero102400ns). In our tests we have used that and most probably this is why it worked for us and not for you. Have corrected that in master now so it should be OK to use both forms.

DanB

**Comment by muxalko** [comment]
Thanks a lot, Dan!
Will try it and get back

**Comment by muxalko** [comment]
After last master update, data usage is working again.
Great thanks !

**Comment by danbogos** [comment]
Thanks for reporting Michael!

Have a good one!

DanB
